/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 19 04:06:38 GMT 2022
 */

package org.apache.commons.math3.fraction;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.math3.FieldElement;
import org.apache.commons.math3.fraction.BigFraction;
import org.apache.commons.math3.fraction.BigFractionField;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BigFractionField_ESTest extends BigFractionField_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BigFractionField bigFractionField0 = BigFractionField.getInstance();
      BigFraction bigFraction0 = bigFractionField0.getZero();
      assertEquals((byte)0, bigFraction0.byteValue());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BigFractionField bigFractionField0 = BigFractionField.getInstance();
      BigFraction bigFraction0 = bigFractionField0.getOne();
      assertEquals((byte)1, bigFraction0.byteValue());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BigFractionField bigFractionField0 = BigFractionField.getInstance();
      Class<? extends FieldElement<BigFraction>> class0 = bigFractionField0.getRuntimeClass();
      assertFalse(class0.isAnnotation());
  }
}
