/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 26 23:40:01 GMT 2022
 */

package org.jfree.chart.block;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.geom.Rectangle2D;
import javax.swing.JInternalFrame;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.block.EmptyBlock;
import org.jfree.chart.block.LineBorder;
import org.jfree.chart.block.RectangleConstraint;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmptyBlock_ESTest extends EmptyBlock_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EmptyBlock emptyBlock0 = new EmptyBlock((-1208.1074319), 50.040771968);
      LineBorder lineBorder0 = new LineBorder();
      emptyBlock0.setFrame(lineBorder0);
      JInternalFrame jInternalFrame0 = new JInternalFrame((String) null);
      Rectangle rectangle0 = jInternalFrame0.getNormalBounds();
      emptyBlock0.draw((Graphics2D) null, (Rectangle2D) rectangle0);
      assertEquals((-1208.1074319), emptyBlock0.getWidth(), 0.01);
      assertEquals(50.040771968, emptyBlock0.getHeight(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EmptyBlock emptyBlock0 = new EmptyBlock((-1208.1074319), 50.040771968);
      LineBorder lineBorder0 = new LineBorder();
      emptyBlock0.setFrame(lineBorder0);
      JInternalFrame jInternalFrame0 = new JInternalFrame((String) null);
      Rectangle rectangle0 = jInternalFrame0.getNormalBounds();
      emptyBlock0.draw((Graphics2D) null, (Rectangle2D) rectangle0, (Object) null);
      assertEquals(50.040771968, emptyBlock0.getHeight(), 0.01);
      assertEquals((-1208.1074319), emptyBlock0.getWidth(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EmptyBlock emptyBlock0 = new EmptyBlock((-1475.115), (-1475.115));
      RectangleConstraint rectangleConstraint0 = new RectangleConstraint((-1.0), 0.0);
      emptyBlock0.arrange((Graphics2D) null, rectangleConstraint0);
      assertEquals((-1475.115), emptyBlock0.getHeight(), 0.01);
      assertEquals((-1475.115), emptyBlock0.getWidth(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EmptyBlock emptyBlock0 = new EmptyBlock(2873L, Double.POSITIVE_INFINITY);
      RectangleConstraint rectangleConstraint0 = new RectangleConstraint(2873L, (-1.0));
      emptyBlock0.arrange((Graphics2D) null, rectangleConstraint0);
      assertEquals(2873.0, emptyBlock0.getWidth(), 0.01);
      assertEquals(Double.POSITIVE_INFINITY, emptyBlock0.getHeight(), 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EmptyBlock emptyBlock0 = new EmptyBlock(0.0, 259.0);
      // Undeclared exception!
      try { 
        emptyBlock0.arrange((Graphics2D) null, (RectangleConstraint) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.block.EmptyBlock", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EmptyBlock emptyBlock0 = new EmptyBlock(1729.468231595, 1729.468231595);
      JScrollPane jScrollPane0 = new JScrollPane();
      JViewport jViewport0 = jScrollPane0.getViewport();
      Rectangle rectangle0 = jViewport0.getViewRect();
      // Undeclared exception!
      try { 
        emptyBlock0.draw((Graphics2D) null, (Rectangle2D) rectangle0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.block.BlockBorder", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      EmptyBlock emptyBlock0 = new EmptyBlock((-1804.90346), 0.0);
      // Undeclared exception!
      try { 
        emptyBlock0.draw((Graphics2D) null, (Rectangle2D) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.util.RectangleInsets", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      EmptyBlock emptyBlock0 = new EmptyBlock(0.8, 0.0);
      RectangleConstraint rectangleConstraint0 = new RectangleConstraint(0.0, 0.8);
      emptyBlock0.arrange((Graphics2D) null, rectangleConstraint0);
      assertEquals(0.0, emptyBlock0.getHeight(), 0.01);
      assertEquals(0.8, emptyBlock0.getWidth(), 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      EmptyBlock emptyBlock0 = new EmptyBlock((-1758.248882087209), (-3561.754911941335));
      EmptyBlock emptyBlock1 = (EmptyBlock)emptyBlock0.clone();
      assertEquals((-1758.248882087209), emptyBlock1.getWidth(), 0.01);
      assertEquals((-3561.754911941335), emptyBlock1.getHeight(), 0.01);
  }
}
