/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 19 23:14:00 GMT 2022
 */

package org.apache.commons.math3.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.math3.exception.NoDataException;
import org.apache.commons.math3.exception.util.LocalizedFormats;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NoDataException_ESTest extends NoDataException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LocalizedFormats localizedFormats0 = LocalizedFormats.LCM_OVERFLOW_32_BITS;
      NoDataException noDataException0 = new NoDataException(localizedFormats0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NoDataException noDataException0 = new NoDataException();
  }
}
