/*
 * This file was automatically generated by EvoSuite
 * Fri Feb 03 21:20:08 GMT 2023
 */

package com.google.gson;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.gson.JsonParseException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JsonParseException_ESTest extends JsonParseException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JsonParseException jsonParseException0 = new JsonParseException("com.google.gson.JsonParseException");
      JsonParseException jsonParseException1 = new JsonParseException("y$R*9'V@,@y4ay_s", jsonParseException0);
      assertFalse(jsonParseException1.equals((Object)jsonParseException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JsonParseException jsonParseException0 = new JsonParseException("com.google.gson.JsonParseException");
      JsonParseException jsonParseException1 = new JsonParseException(jsonParseException0);
      assertFalse(jsonParseException1.equals((Object)jsonParseException0));
  }
}
