/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 26 23:15:14 GMT 2022
 */

package org.jfree.chart.editor;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.editor.ChartEditorFactory;
import org.jfree.chart.editor.ChartEditorManager;
import org.jfree.chart.editor.DefaultChartEditor;
import org.jfree.chart.editor.DefaultChartEditorFactory;
import org.jfree.chart.plot.FastScatterPlot;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChartEditorManager_ESTest extends ChartEditorManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultChartEditorFactory defaultChartEditorFactory0 = new DefaultChartEditorFactory();
      ChartEditorManager.setChartEditorFactory(defaultChartEditorFactory0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FastScatterPlot fastScatterPlot0 = new FastScatterPlot();
      JFreeChart jFreeChart0 = new JFreeChart(fastScatterPlot0);
      DefaultChartEditor defaultChartEditor0 = (DefaultChartEditor)ChartEditorManager.getChartEditor(jFreeChart0);
      assertFalse(defaultChartEditor0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        ChartEditorManager.setChartEditorFactory((ChartEditorFactory) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null 'f' argument.
         //
         verifyException("org.jfree.chart.editor.ChartEditorManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        ChartEditorManager.getChartEditor((JFreeChart) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.editor.DefaultChartEditor", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ChartEditorFactory chartEditorFactory0 = ChartEditorManager.getChartEditorFactory();
      ChartEditorManager.setChartEditorFactory(chartEditorFactory0);
  }
}
