/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 20 00:30:49 GMT 2022
 */

package org.apache.commons.math3.analysis.function;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math3.analysis.differentiation.DerivativeStructure;
import org.apache.commons.math3.analysis.function.Constant;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Constant_ESTest extends Constant_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Constant constant0 = new Constant(0.0);
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 0);
      DerivativeStructure derivativeStructure1 = constant0.value(derivativeStructure0);
      assertEquals(0.0, derivativeStructure1.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Constant constant0 = new Constant((-4572.3233523992));
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 2912);
      DerivativeStructure derivativeStructure1 = constant0.value(derivativeStructure0);
      assertEquals((-4572.3233523992), derivativeStructure1.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Constant constant0 = new Constant(332.0);
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(96, 0);
      DerivativeStructure derivativeStructure1 = constant0.value(derivativeStructure0);
      assertEquals(332.0, derivativeStructure1.getValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Constant constant0 = new Constant(0.0);
      double double0 = constant0.value(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Constant constant0 = new Constant(2.0);
      double double0 = constant0.value(2.0);
      assertEquals(2.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Constant constant0 = new Constant(0.0);
      // Undeclared exception!
      try { 
        constant0.value((DerivativeStructure) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math3.analysis.function.Constant", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Constant constant0 = new Constant((-15.93392762620854));
      double double0 = constant0.value((-15.93392762620854));
      assertEquals((-15.93392762620854), double0, 0.01);
  }
}
