/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 27 00:48:08 GMT 2022
 */

package org.jfree.chart.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import java.text.AttributedCharacterIterator;
import java.text.AttributedString;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jfree.chart.util.AttributedStringUtilities;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AttributedStringUtilities_ESTest extends AttributedStringUtilities_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AttributedString attributedString0 = new AttributedString("L5kyBCoAYO+,");
      AttributedString attributedString1 = new AttributedString("k2F6d#q]$_b");
      boolean boolean0 = AttributedStringUtilities.equal(attributedString0, attributedString1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AttributedCharacterIterator attributedCharacterIterator0 = mock(AttributedCharacterIterator.class, new ViolatedAssumptionAnswer());
      doReturn('a').when(attributedCharacterIterator0).current();
      doReturn(0).when(attributedCharacterIterator0).getBeginIndex();
      doReturn(0).when(attributedCharacterIterator0).getEndIndex();
      doReturn(0).when(attributedCharacterIterator0).getIndex();
      doReturn('a').when(attributedCharacterIterator0).setIndex(anyInt());
      AttributedCharacterIterator.Attribute[] attributedCharacterIterator_AttributeArray0 = new AttributedCharacterIterator.Attribute[4];
      AttributedString attributedString0 = new AttributedString(attributedCharacterIterator0, 0, 0, attributedCharacterIterator_AttributeArray0);
      HashMap<AttributedCharacterIterator.Attribute, Object> hashMap0 = new HashMap<AttributedCharacterIterator.Attribute, Object>();
      AttributedString attributedString1 = new AttributedString("g+a1*qoP7*s4=", hashMap0);
      boolean boolean0 = AttributedStringUtilities.equal(attributedString0, attributedString1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AttributedString attributedString0 = new AttributedString("&S}KC6dlbI~nccC~RS7");
      AttributedCharacterIterator.Attribute attributedCharacterIterator_Attribute0 = AttributedCharacterIterator.Attribute.LANGUAGE;
      Object object0 = new Object();
      attributedString0.addAttribute(attributedCharacterIterator_Attribute0, object0);
      HashMap<AttributedCharacterIterator.Attribute, Object> hashMap0 = new HashMap<AttributedCharacterIterator.Attribute, Object>();
      AttributedString attributedString1 = new AttributedString("&S}KC6dlbI~nccC~RS7", hashMap0);
      boolean boolean0 = AttributedStringUtilities.equal(attributedString0, attributedString1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HashMap<AttributedCharacterIterator.Attribute, AttributedCharacterIterator.Attribute> hashMap0 = new HashMap<AttributedCharacterIterator.Attribute, AttributedCharacterIterator.Attribute>();
      AttributedString attributedString0 = new AttributedString("e;uNUATirE", hashMap0);
      AttributedString attributedString1 = new AttributedString("=`g$NB~lAIN.jl,sMe", hashMap0);
      boolean boolean0 = AttributedStringUtilities.equal(attributedString0, attributedString1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AttributedString attributedString0 = new AttributedString("&S}KC6dlbI~nccC~RS7");
      boolean boolean0 = AttributedStringUtilities.equal(attributedString0, attributedString0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AttributedString attributedString0 = new AttributedString("&S}KC6dlbI~nccC~RS7");
      boolean boolean0 = AttributedStringUtilities.equal(attributedString0, (AttributedString) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AttributedString attributedString0 = new AttributedString("&S}KC6dlbI~nccC~RS7");
      boolean boolean0 = AttributedStringUtilities.equal((AttributedString) null, attributedString0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      boolean boolean0 = AttributedStringUtilities.equal((AttributedString) null, (AttributedString) null);
      assertTrue(boolean0);
  }
}
