/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 02 02:12:55 GMT 2023
 */

package org.apache.commons.jxpath.ri.model.dynamic;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Locale;
import org.apache.commons.jxpath.Variables;
import org.apache.commons.jxpath.ri.QName;
import org.apache.commons.jxpath.ri.model.NodePointer;
import org.apache.commons.jxpath.ri.model.VariablePointer;
import org.apache.commons.jxpath.ri.model.dynamic.DynamicPointerFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DynamicPointerFactory_ESTest extends DynamicPointerFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DynamicPointerFactory dynamicPointerFactory0 = new DynamicPointerFactory();
      QName qName0 = new QName("");
      VariablePointer variablePointer0 = new VariablePointer((Variables) null, qName0);
      NodePointer nodePointer0 = dynamicPointerFactory0.createNodePointer((NodePointer) variablePointer0, qName0, (Object) null);
      assertNull(nodePointer0.getNamespaceURI());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DynamicPointerFactory dynamicPointerFactory0 = new DynamicPointerFactory();
      Locale locale0 = Locale.CHINESE;
      // Undeclared exception!
      try { 
        dynamicPointerFactory0.createNodePointer((QName) null, (Object) null, locale0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.jxpath.ri.model.dynamic.DynamicPointerFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DynamicPointerFactory dynamicPointerFactory0 = new DynamicPointerFactory();
      QName qName0 = new QName("\"z%b^:}6zEdeXjtGo^");
      NodePointer nodePointer0 = dynamicPointerFactory0.createNodePointer((NodePointer) null, qName0, (Object) null);
      assertTrue(nodePointer0.isRoot());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DynamicPointerFactory dynamicPointerFactory0 = new DynamicPointerFactory();
      QName qName0 = new QName("\"z%b^:}6zEdeXjtGo^");
      NodePointer nodePointer0 = dynamicPointerFactory0.createNodePointer((NodePointer) null, qName0, (Object) "\"z%b^:}6zEdeXjtGo^");
      assertNull(nodePointer0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DynamicPointerFactory dynamicPointerFactory0 = new DynamicPointerFactory();
      QName qName0 = new QName("\"z%b^:}6zEdeXjtGo^");
      Locale locale0 = Locale.GERMAN;
      NodePointer nodePointer0 = dynamicPointerFactory0.createNodePointer(qName0, (Object) "\"z%b^:}6zEdeXjtGo^", locale0);
      assertNull(nodePointer0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DynamicPointerFactory dynamicPointerFactory0 = new DynamicPointerFactory();
      int int0 = dynamicPointerFactory0.getOrder();
      assertEquals(800, int0);
  }
}
