/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 12 22:51:23 GMT 2023
 */

package com.google.javascript.jscomp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.javascript.jscomp.JsMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JsMessage_ESTest extends JsMessage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JsMessage.PlaceholderReference jsMessage_PlaceholderReference0 = new JsMessage.PlaceholderReference("%(`rx1u");
      char char0 = jsMessage_PlaceholderReference0.charAt(0);
      assertEquals('%', char0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JsMessage.Builder jsMessage_Builder0 = null;
      try {
        jsMessage_Builder0 = new JsMessage.Builder("CLOSURE");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/collect/Lists
         //
         verifyException("com.google.javascript.jscomp.JsMessage$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("QMo[ZbW}I[TJN`-kza");
      assertEquals((-4070022004969983079L), long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("{@Z%QB8\"/Hs*7q");
      assertEquals((-2662115047452579513L), long0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("{@Z%QB8\"/Hs*q");
      assertEquals(7337636155389816156L, long0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("@*uGiFhv.-QY");
      assertEquals((-6187936515904984206L), long0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("ELT xh56vj");
      assertEquals((-8373938196860935820L), long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("ELTxh56vj");
      assertEquals((-3985814554370993893L), long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("ET xh56j");
      assertEquals(566820639753416288L, long0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("CLOSURE");
      assertEquals((-3515084970280262129L), long0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("LEGACY");
      assertEquals((-6953637779535637714L), long0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("Z.>h,");
      assertEquals((-2910512845914916198L), long0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("|gNZ");
      assertEquals(1972857340349101298L, long0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("XUv");
      assertEquals(3094040368405783532L, long0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("Rl");
      assertEquals(5836867074589187132L, long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("v");
      assertEquals(8083837897678526886L, long0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64((String) null);
      assertEquals(5083893976283701674L, long0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      JsMessage.PlaceholderReference jsMessage_PlaceholderReference0 = new JsMessage.PlaceholderReference("%(`rx1u");
      boolean boolean0 = jsMessage_PlaceholderReference0.equals("%(`rx1u");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      JsMessage.Style jsMessage_Style0 = JsMessage.Style.getFromParams(true, true);
      assertEquals(JsMessage.Style.RELAX, jsMessage_Style0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      JsMessage.Style jsMessage_Style0 = JsMessage.Style.getFromParams(true, false);
      assertEquals(JsMessage.Style.CLOSURE, jsMessage_Style0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      JsMessage.Style jsMessage_Style0 = JsMessage.Style.getFromParams(false, false);
      assertEquals(JsMessage.Style.LEGACY, jsMessage_Style0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      JsMessage.PlaceholderReference jsMessage_PlaceholderReference0 = new JsMessage.PlaceholderReference("");
      int int0 = jsMessage_PlaceholderReference0.length();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      JsMessage.PlaceholderReference jsMessage_PlaceholderReference0 = new JsMessage.PlaceholderReference("");
      String string0 = jsMessage_PlaceholderReference0.toString();
      assertEquals("{$}", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      JsMessage.PlaceholderReference jsMessage_PlaceholderReference0 = new JsMessage.PlaceholderReference("");
      CharSequence charSequence0 = jsMessage_PlaceholderReference0.subSequence(0, 0);
      assertEquals("", charSequence0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      JsMessage.PlaceholderReference jsMessage_PlaceholderReference0 = new JsMessage.PlaceholderReference("");
      String string0 = jsMessage_PlaceholderReference0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      JsMessage.Builder jsMessage_Builder0 = null;
      try {
        jsMessage_Builder0 = new JsMessage.Builder();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/collect/Lists
         //
         verifyException("com.google.javascript.jscomp.JsMessage$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      long long0 = JsMessage.Hash.hash64("@gwyoi\u0007!B<K,=G'");
      assertEquals(2534012588351929787L, long0);
  }
}
