/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 16 18:18:04 GMT 2023
 */

package com.google.javascript.jscomp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.javascript.jscomp.JvmMetrics;
import java.io.PrintStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JvmMetrics_ESTest extends JvmMetrics_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        JvmMetrics.maybeWriteJvmMetrics((PrintStream) null, "2j-T+Z097%#JJ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.JvmMetrics", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("%NF;NVJB{+\"@E;=H`");
      JvmMetrics.maybeWriteJvmMetrics(mockPrintStream0, "t^ /@aSV^:HqJ77U:%");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("%NF;NVJB{+\"@E;=H`");
      JvmMetrics.maybeWriteJvmMetrics(mockPrintStream0, "verbose");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("[;;o!4r/");
      JvmMetrics.maybeWriteJvmMetrics(mockPrintStream0, "w\n|/g(9&'am[)");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("[;;o!4r/");
      JvmMetrics.maybeWriteJvmMetrics(mockPrintStream0, (String) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("%NF;NVJB{+\"@E;=H`");
      JvmMetrics.maybeWriteJvmMetrics(mockPrintStream0, "");
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JvmMetrics jvmMetrics0 = new JvmMetrics();
  }
}
