/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 12 22:47:43 GMT 2023
 */

package com.google.javascript.jscomp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.javascript.jscomp.NodeNameExtractor;
import com.google.javascript.rhino.Node;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NodeNameExtractor_ESTest extends NodeNameExtractor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NodeNameExtractor nodeNameExtractor0 = new NodeNameExtractor('T');
      Node node0 = new Node('T');
      nodeNameExtractor0.getName(node0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NodeNameExtractor nodeNameExtractor0 = new NodeNameExtractor(')');
      Node node0 = new Node(154, 154, ')');
      // Undeclared exception!
      try { 
        nodeNameExtractor0.getName(node0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // STRING_KEY 154 is not a string node
         //
         verifyException("com.google.javascript.rhino.Node", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Node node0 = new Node(105, 105, 1168);
      NodeNameExtractor nodeNameExtractor0 = new NodeNameExtractor(' ');
      // Undeclared exception!
      try { 
        nodeNameExtractor0.getName(node0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.NodeNameExtractor", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Node node0 = new Node(42, 43, 4095);
      NodeNameExtractor nodeNameExtractor0 = new NodeNameExtractor('(');
      nodeNameExtractor0.getName(node0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Node node0 = new Node(40, 40, 40);
      NodeNameExtractor nodeNameExtractor0 = new NodeNameExtractor('t');
      // Undeclared exception!
      try { 
        nodeNameExtractor0.getName(node0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // String node not created with Node.newString
         //
         verifyException("com.google.javascript.rhino.Node", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Node node0 = new Node(39, 'Q', (-581));
      NodeNameExtractor nodeNameExtractor0 = new NodeNameExtractor('(');
      // Undeclared exception!
      try { 
        nodeNameExtractor0.getName(node0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // com/google/common/base/Predicate
         //
         verifyException("com.google.javascript.jscomp.NodeNameExtractor", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      NodeNameExtractor nodeNameExtractor0 = new NodeNameExtractor('T');
      Node node0 = new Node(38, 31, 15);
      // Undeclared exception!
      try { 
        nodeNameExtractor0.getName(node0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // NAME 31 is not a string node
         //
         verifyException("com.google.javascript.rhino.Node", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      NodeNameExtractor nodeNameExtractor0 = new NodeNameExtractor('0');
      Node node0 = new Node(37);
      // Undeclared exception!
      try { 
        nodeNameExtractor0.getName(node0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.NodeNameExtractor", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Node node0 = new Node(35, (-280), 1352);
      NodeNameExtractor nodeNameExtractor0 = new NodeNameExtractor('`');
      // Undeclared exception!
      try { 
        nodeNameExtractor0.getName(node0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.NodeNameExtractor", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      NodeNameExtractor nodeNameExtractor0 = new NodeNameExtractor('P');
      Node node0 = new Node(33);
      // Undeclared exception!
      try { 
        nodeNameExtractor0.getName(node0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.javascript.jscomp.NodeNameExtractor", e);
      }
  }
}
