/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 26 20:16:11 GMT 2022
 */

package org.jfree.data.pie;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import java.sql.Connection;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jfree.data.jdbc.JDBCPieDataset;
import org.jfree.data.pie.AbstractPieDataset;
import org.jfree.data.pie.PieDatasetSelectionState;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractPieDataset_ESTest extends AbstractPieDataset_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Connection connection0 = mock(Connection.class, new ViolatedAssumptionAnswer());
      JDBCPieDataset jDBCPieDataset0 = new JDBCPieDataset(connection0);
      PieDatasetSelectionState pieDatasetSelectionState0 = jDBCPieDataset0.getSelectionState();
      assertSame(pieDatasetSelectionState0, jDBCPieDataset0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AbstractPieDataset abstractPieDataset0 = new AbstractPieDataset();
      abstractPieDataset0.setSelectionState((PieDatasetSelectionState) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AbstractPieDataset abstractPieDataset0 = new AbstractPieDataset();
      PieDatasetSelectionState pieDatasetSelectionState0 = abstractPieDataset0.getSelectionState();
      assertNull(pieDatasetSelectionState0);
  }
}
