/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 27 03:27:29 GMT 2022
 */

package org.jfree.chart.text;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.font.FontRenderContext;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jfree.chart.text.G2TextMeasurer;
import org.jfree.chart.text.TextUtilities;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class G2TextMeasurer_ESTest extends G2TextMeasurer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FontMetrics fontMetrics0 = mock(FontMetrics.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(fontMetrics0).getAscent();
      doReturn(0).when(fontMetrics0).getHeight();
      doReturn(0).when(fontMetrics0).stringWidth(anyString());
      Graphics2D graphics2D0 = mock(Graphics2D.class, new ViolatedAssumptionAnswer());
      doReturn(fontMetrics0).when(graphics2D0).getFontMetrics();
      G2TextMeasurer g2TextMeasurer0 = new G2TextMeasurer(graphics2D0);
      TextUtilities.setUseFontMetricsGetStringBounds(false);
      float float0 = g2TextMeasurer0.getStringWidth("", 0, 0);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FontMetrics fontMetrics0 = mock(FontMetrics.class, new ViolatedAssumptionAnswer());
      doReturn(313).when(fontMetrics0).getAscent();
      doReturn(3265).when(fontMetrics0).getHeight();
      doReturn(313).when(fontMetrics0).stringWidth(anyString());
      Graphics2D graphics2D0 = mock(Graphics2D.class, new ViolatedAssumptionAnswer());
      doReturn(fontMetrics0).when(graphics2D0).getFontMetrics();
      G2TextMeasurer g2TextMeasurer0 = new G2TextMeasurer(graphics2D0);
      TextUtilities.setUseFontMetricsGetStringBounds(false);
      float float0 = g2TextMeasurer0.getStringWidth("", 0, 0);
      assertEquals(313.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FontMetrics fontMetrics0 = mock(FontMetrics.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(fontMetrics0).getAscent();
      doReturn(0).when(fontMetrics0).getHeight();
      doReturn((-185)).when(fontMetrics0).stringWidth(anyString());
      Graphics2D graphics2D0 = mock(Graphics2D.class, new ViolatedAssumptionAnswer());
      doReturn(fontMetrics0).when(graphics2D0).getFontMetrics();
      G2TextMeasurer g2TextMeasurer0 = new G2TextMeasurer(graphics2D0);
      TextUtilities.setUseFontMetricsGetStringBounds(false);
      float float0 = g2TextMeasurer0.getStringWidth("", 0, 0);
      assertEquals((-185.0F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FontMetrics fontMetrics0 = mock(FontMetrics.class, new ViolatedAssumptionAnswer());
      Graphics2D graphics2D0 = mock(Graphics2D.class, new ViolatedAssumptionAnswer());
      doReturn(fontMetrics0).when(graphics2D0).getFontMetrics();
      G2TextMeasurer g2TextMeasurer0 = new G2TextMeasurer(graphics2D0);
      // Undeclared exception!
      try { 
        g2TextMeasurer0.getStringWidth("", 0, 567);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FontMetrics fontMetrics0 = mock(FontMetrics.class, new ViolatedAssumptionAnswer());
      doReturn((Font) null).when(fontMetrics0).getFont();
      doReturn((Rectangle2D) null).when(fontMetrics0).getStringBounds(anyString() , any(java.awt.Graphics.class));
      Graphics2D graphics2D0 = mock(Graphics2D.class, new ViolatedAssumptionAnswer());
      doReturn(fontMetrics0).when(graphics2D0).getFontMetrics();
      doReturn((FontRenderContext) null).when(graphics2D0).getFontRenderContext();
      G2TextMeasurer g2TextMeasurer0 = new G2TextMeasurer(graphics2D0);
      // Undeclared exception!
      try { 
        g2TextMeasurer0.getStringWidth("", 0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.text.TextUtilities", e);
      }
  }
}
